demo-foundations:
	python3 src/foundations.py

demo-logs:
	python3 src/logs_and_traces.py

demo-debugging:
	python3 src/debugging_tools.py

demo-monitor:
	python3 src/resource_monitoring.py

.PHONY: demo-foundations demo-logs demo-debugging demo-monitor

demo-async:
	python3 src/async_debug.py

.PHONY: demo-foundations demo-logs demo-debugging demo-monitor